<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="user-PC" ignored="0" name="Regression" tests="7" failures="1" timestamp="31 Oct 2022 02:34:11 GMT" time="154.115" errors="0">
  <testcase name="verify_InvalidLoginCredentialAlertMessage" time="1.064" classname="com.supermarket.tests.LoginTest">
    <failure type="java.lang.AssertionError" message="This testcase failed expected [Alert!] but found [×
Alert!
Invalid Username/Password]">
      <![CDATA[java.lang.AssertionError: This testcase failed expected [Alert!] but found [×
Alert!
Invalid Username/Password]
	at com.supermarket.tests.LoginTest.verify_InvalidLoginCredentialAlertMessage(LoginTest.java:42)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- verify_InvalidLoginCredentialAlertMessage -->
  <testcase name="verify_Login" time="0.854" classname="com.supermarket.tests.LoginTest"/>
  <testcase name="verify_ProfileImageisDisplayed" time="5.781" classname="com.supermarket.tests.LoginTest"/>
  <testcase name="verify_AlertTextPushNotificationByDataProviderClass" time="4.374" classname="com.supermarket.tests.PushNotificationTest"/>
  <testcase name="verify_AlertTextPushNotificationByDataProviderClass" time="3.35" classname="com.supermarket.tests.PushNotificationTest"/>
  <testcase name="verify_AlertTextPushNotificationByDataProviderClass" time="3.514" classname="com.supermarket.tests.PushNotificationTest"/>
  <testcase name="verify_SuccessAlertPushNotification" time="6.928" classname="com.supermarket.tests.PushNotificationTest"/>
</testsuite> <!-- Regression -->
